#KeyHistory 0
#b::Run https://hh.blackboard.com/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_98_1
#p::Run C:\Users\E\Desktop\PROJEKT
#w::Run http://www.wolframalpha.com/
#s::Run C:\AutoHotKeys
#h::Run C:\Users\E\Downloads
#t::Run https://translate.google.se/
#n::Run notepad++.exe
#1::Run https://se.timeedit.net/web/hh/db1/schema/ri155XQm661Z5QQv77000Zq6yZY780fQ7YZ5Y5gQ1076q60Z6Qy300QZZbQQZolQuoofnc.html
#g::Run https://www.google.se
#ö::Run C:\Users\E\workspace\Photographic_memory\src\frågor.txt
#ä::Run C:\Users\E\Desktop\PROJEKT\ö_andrahand\ÖVRIGT\HTML
#å::Run C:\Users\E\Desktop\PROJEKT\TID_GLOBAL_2016jan.xlsx
#x::Run https://drive.google.com/drive/folders/0BxiV9Hbd4VQfYW1yMjV3ZWxqSkE
